// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffizeamocbulejebasxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmaXplYW1vY2J1bGVqZWJhc3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTQ2NTQsImV4cCI6MjA3MTc3MDY1NH0.T-FuO2ZSAVzqqtFrY02HnKPlBYTq0i7VcUrTbpTFXjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});